Repository eccentriccoder01/TalkHeal, pull requests merged in 2025-09, with the labels that each got.

#144 feat: add pin/unpin messages in chat and pinned messages page
  TalkHeal.py
  components/chat_interface.py
  components/sidebar.py
  pages/Pinned_msg.py
Labels: enhancement, gssoc25, level 2

#163 chore: cleanup requirements.txt (remove duplicate pandas)
  requirements.txt
Labels: documentation, good first issue, gssoc25, level 2

#166 chore: clean imports and minor dead code removal (#153)
  TalkHeal.py
  components/chat_interface.py
  components/sidebar.py
  core/config.py
Labels: good first issue, gssoc25, level 2

#185 Fix: Sync user profile name across signup, sidebar, and main window (#169)
  TalkHeal.py
  components/login_page.py
  components/reset_page.py
Labels: bug, gssoc25, level 3

#186 Add simple footer component
  components/footer.py
Labels: enhancement, gssoc25, level 3

#190 Added privacy policy page
  TalkHeal.py
  components/footer.py
  pages/AppOverview.py
  pages/Blog.py
  pages/Careers.py
  pages/Community.py
  pages/ContactUs.py
  pages/CookiePolicy.py
  pages/CopyrightNotice.py
  pages/Disclaimer.py
  pages/FAQs.py
  pages/HelpCenter.py
  pages/NewsletterSignup.py
  pages/PrivacyPolicy.py
  pages/SocialMedia.py
  pages/TermsOfService.py
Labels: enhancement, gssoc25, level 3

#194 Add styled Copyright Notice page
  pages/CopyrightNotice.py
Labels: enhancement, gssoc25, level 3

#199 Added career page in the footer
  pages/Careers.py
Labels: enhancement, gssoc25, level 3

#201 Added help center page
  pages/HelpCenter.py
Labels: enhancement, gssoc25, level 3

#195 Fix: Change login validation message from warning to error.
  components/login_page.py
Labels: enhancement, gssoc25, level 2

#209 Added a community page
  pages/Community.py
  pages/HelpCenter.py
Labels: enhancement, gssoc25, level 3

#196 feat: Add Guest Login functionality
  components/login_page.py
Labels: gssoc25, level 2

#226 [FEATURE] Add Feedback Buttons for Chatbot Responses #162
  components/chat_interface.py
  core/utils.py
  setup_database.py
Labels: enhancement, gssoc25, level 2

#229 [BUG] Authentication-related messages are barely visible. #160
  components/login_page.py
Labels: bug, gssoc25, level 2

#225 feat: add Habit Builder Pro application with tracking and analytics
  pages/Habit_Builder.py
Labels: enhancement, gssoc25, level 3

#231 Community forum
  TalkHeal.py
  app.py
  components/sidebar.py
  pages/AppOverview.py
  pages/CommunityForum.py
Labels: enhancement, gssoc25, level 3

#232 User Authentication Lost on Page Navigation in Journaling Section #170
  TalkHeal.py
  components/login_page.py
  core/utils.py
  pages/Journaling.py
Labels: bug, gssoc25, level 3

#241 login
  components/login_page.py
Labels: bug, gssoc25, level 3

#239 Changes made in the Visibility of Links in the knowledge section
  pages/selfHelpTools.py
Labels: gssoc25, level 1

#245 Game1
  TalkHeal.py
  components/games.py
Labels: enhancement, gssoc25, level 3

#253 fixed the issues arising in the gamification section
  TalkHeal.py
  components/games.py
  components/games_breathing_pattern.py
  components/games_memory_only.py
  components/games_mood_color.py
  components/games_stress_clicker.py
  components/games_word_association.py
Labels: enhancement, gssoc25, level 3

#254 Added readability on narrow screen
  TalkHeal.py
  components/games.py
  core/utils.py
  css/styles.py
Labels: enhancement, gssoc25, level 3

#255 added 2 more cards wellness resource hub and habit builder
  TalkHeal.py
Labels: gssoc25, level 3

#256 Added 5 cards per row
  TalkHeal.py
Labels: enhancement, gssoc25, level 3

#257 added borders
  TalkHeal.py
  css/styles.py
Labels: gssoc25, level 3

#264 feat(doctor_spec): improve disease prediction results display
  pages/doctor_spec.py
Labels: enhancement, gssoc25, level 2

#276 Improve Copy Right Notice Page styling and structure
  pages/CopyrightNotice.py
Labels: enhancement, gssoc25, level 2

#293 Enhance Community Forum with Post Storage, Replies, and Moderation (Fixes #291)
  pages/CommunityForum.py
Labels: enhancement, gssoc25, level 3

#297 Upgrade Breathing Exercise: Replace CSS Animation with Lottie for Modern UX
  pages/Breathing_Exercise.py
Labels: enhancement, gssoc25, level 3

#333 Enhanced Crisis Support with Country Selection
  pages/selfHelpTools.py
Labels: enhancement, gssoc25, level 3
